[package]
name = "personal-makeshift-screenreader"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.31.1", features = ["persistence", "ron"] }
serde = { version = "1.0.219", features = ["derive"] }
